# Generated by Django 3.1.7 on 2021-03-16 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tips', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tips',
            name='retweeted',
            field=models.BooleanField(default=False),
        ),
    ]
