# Generated by Django 3.1.7 on 2021-03-10 23:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('twitterapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='twitterauth',
            name='screen_name',
            field=models.CharField(default=None, max_length=255),
            preserve_default=False,
        ),
    ]
